<?php
$termsUrl = $block->getBaseUrl();
$fetchProduct = $block->getLayout()->createBlock('Nailalliance\ProConfirmation\Block\FetchProduct');
$currentProduct = $fetchProduct->getCurrentProduct();
$prodID = $currentProduct->getId();
$productRepo = $fetchProduct->getProductById($prodID);
$isProfessional = $productRepo['isprofessional'];
?>
<noscript>
    <div class="no-script-container">
        <p>This page won't function properly without JavaScript enabled. Please enable JavaScript.</p>
    </div>
    <style>
        .no-script-container {
            position: absolute;
            z-index: 99999;
            background: #fff;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 100%;
            height: 100%;
            padding: 1rem;
            margin: 1rem;
            text-align: center;
        }

        body {
            overflow: hidden !important;
        }

        .nts-announcement-container {
            display: none !important;
        }

        #product-addtocart-button {
            display: none !important;
        }
        
        .paypal.checkout {
            display: none !important;
        }

        .product-add-form {
            display: none !important;
        }

        #pro-confirm {
            display: none !important;
        }

        .field.qty {
            display: none !important;
        }

        #cross-related-products {
            display: none !important;
        }

        .message.global.noscript,
        .message.global.cookie {
            text-align: center;
        }
    </style>
</noscript>

<?php if ($isProfessional == 1) : ?>
    <div class="pro-conf-container" id="pro-confirm">
        <div class="pro-heading">
            <h3>Professional Beauty Confirmation - Required</h3>
        </div>
        <div class="pro-confirm-details pcf1">
            <p>By ticking the checkbox below, you are agreeing to our website's <a class="pcf-terms-link" href="<?= $termsUrl . 'terms-and-conditions' ?>">Terms &amp; Conditions</a></p>
        </div>
        <div class="pro-confirm-details pcf2">
            <label for="pro-checkbox">Professional use only - Tick to confirm you are a beauty professional. May cause an allergic reaction.</label>
            <br>
            <input id="pro-checkbox" name="pro-checkbox" type="checkbox" class="pcf-checkbox">Yes</input>
        </div>
    </div>
    <script type="text/javascript">
        let professionalChecked = false;
        let addBtn = document.getElementById("product-addtocart-button");
        let paypalBtn = document.querySelector(".paypal.checkout");
        addBtn.classList.add("pro-btn-disabled");
        paypalBtn.classList.add("pro-btn-disabled");
        document.querySelector(".pcf-checkbox").addEventListener('click', function() {
            if (professionalChecked == false) {
                professionalChecked = true;
                addBtn.disabled = false;
                addBtn.classList.remove("pro-btn-disabled");
                paypalBtn.classList.remove("pro-btn-disabled");

            } else {
                professionalChecked = false;
                addBtn.disabled = true;
                addBtn.classList.add("pro-btn-disabled");
                paypalBtn.classList.add("pro-btn-disabled");
            }
        });
    </script>
<?php endif; ?>